[build]
rustflags = [
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "lto=thin",
    "-C", "panic=abort",
    "-C", "debuginfo=0",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=x86-64-v3",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,-O2",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "target-cpu=x86-64-v3",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,-O2",
]

# For ARM (AWS Graviton/Neoverse)
[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=neoverse-n1",
    "-C", "link-arg=-Wl,--gc-sections",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-cpu=x86-64-v3",
    "-C", "link-arg=/OPT:REF",
    "-C", "link-arg=/OPT:ICF",
    "-C", "link-arg=/Brepro",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=apple-m1",
    "-C", "link-arg=-Wl,-dead_strip",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=x86-64-v3",
    "-C", "link-arg=-Wl,-dead_strip",
]
